### ISSUE TITLE
Dash vs. Shiny vs. Superset

### ISSUE THREAD

**Issue by JamesKunstle** [sandiego-rh/sandiego#107]
There are a number of potential framework alternatives for the dashboard front-end. Choosing between them is not a one-shot task given the number of development variables- testing maturity, support, scalability, features, etc. 

A good first pass is required to start the decision-making process, however. Therefore, a small example dashboard ought to be developed in each of the current potential frameworks: Shiny (R), Superset, and Kivy (Python).

**I've scrapped the boiler-plate on this issue because I'm (@JamesKunstle) most likely going to be taking on this ticket.

Associated issue: #113

**Comment by JamesKunstle** [comment]
++ demo in kivy if possible.

**Comment by cdolfi** [comment]
Question around superset: what are the options for a visualization that will take some preprocessing beyond counting/mean/etc
example: the survival visualizations by james

**Comment by cdolfi** [comment]
@GregSutcliffe with a shiny demo on the way!

**Comment by JamesKunstle** [comment]
I've updates the title- old tile was: Shiny vs. Kivy vs. Superset. I don't think that Kivy will do what we want, and instead we should spend our time on Dash. Here are some useful docs and motivations of Dash:

https://dash.plotly.com/layout

https://medium.com/plotly/introducing-dash-5ecf7191b503

**Comment by cdolfi** [comment]
Closing this as we will be moving forward with dash
