### ISSUE TITLE
Sprint 7: Discussion around sections and topic areas for the dashboard

### ISSUE THREAD

**Issue by cdolfi** [sandiego-rh/sandiego#112]
This is a part of the extended series of development for dashboard visualizations. Let this be the place where people can put their new ideas for visualizations or to voice the questions they would like to see answered.

This cycle, the focus is going to step back from specific visualizations to sections and topic areas for the dashboard. 

There will be a design session for the dashboard in mid December and we are looking for feedback from what coverage people would like to see. 

Some questions to think about: 

- What are some general topic areas for coverage on a repo/project? (Contributor break down, PR activity, Security, etc)
- Is there extended questions to be answered from the perspective of a community member or an outsider looking in? 

More to be added

**Comment by cdolfi** [comment]
@thewizzy Curious if you or any security folks have any input on this

**Comment by thewizzy** [comment]
From a security point of view there are metrics that are useful, the [ OpenSSF Scorecard checks](https://github.com/ossf/scorecard#scorecard-checks) cover many of these well. The CHAOSS[ Risk WG](https://github.com/chaoss/wg-risk) is also working on a number that would be useful.

Many of the signals signals that point to a healthy project/project engagement are likely going to indicate a project that will respond well to security issues.
