### ISSUE TITLE
Augur DB: Coordinate solution to allow for collection without hurting query run time

### ISSUE THREAD

**Issue by cdolfi** [sandiego-rh/sandiego#145]
It has been identified that collection causes serious slow down for querying the data base. A short term and long term solution might have to be identified to solve this problem. 

Potential Solutions: 

- Create a second DB for collection 
- Do collection over the weekend (potential issue with incomplete data, must determine if it can be completed in the time period so this is not an issue)

**Comment by jasonbrooks** [comment]
Let's begin by collecting some information. Let's take a few specific queries, and measure their run times when collection is and isn't happening. Also, are we running two instances of augur at once -- the red and blue? When do those run and what's the impact of running one or both on query run times? We might also be able to do things to optimize these queries.

During what hours are we typically running queries? Is the leftover time enough to complete collection? We could schedule the starting and stopping of augur to limit collection to times that we aren't running queries.

**Comment by cdolfi** [comment]
That works for me! When collection is running, one easy place to look at behavior of a few queries is looking to see how long it takes the dash app to complete all the queries in there (about 5-6 at this time). 

We are typically running queries in EST working hours (10-5, shorter on fridays usually, potentially after 5pm EST on other days). For weekly connections I wonder if starting at 5 on friday would give enough time for it to be done by midday on Monday as usually the first few hours is meetings and catching up on comms. Curious to hear peoples thoughts!

**Comment by jasonbrooks** [comment]
> That works for me! When collection is running, one easy place to look at behavior of a few queries is looking to see how long it takes the dash app to complete all the queries in there (about 5-6 at this time).

Can you link to the dash app queries?

> 
> We are typically running queries in EST working hours (10-5, shorter on fridays usually, potentially after 5pm EST on other days). For weekly connections I wonder if starting at 5 on friday would give enough time for it to be done by midday on Monday as usually the first few hours is meetings and catching up on comms. Curious to hear peoples thoughts!

We can make a cron job to start the collection each evening and stop it before the workday, and all day during the weekend.

**Comment by cdolfi** [comment]
Update the call backs are all here: https://github.com/sandiego-rh/explorer/blob/main/query_callbacks.py

**Comment by jasonbrooks** [comment]
That's great about the systemd unit file, Sean. LMK when you put that shell script in place.

On the materialized views, let's discuss specifically what we need for that.

**Comment by sgoggins** [comment]
@jasonbrooks : it is created here: `/home/augur/github/augur-red/sandiego_service.sh` ... any user should be able to execute it. Right now we are running augur, so we should talk about when to restart it using a service file.
