### ISSUE TITLE
OSS Demo generation

### ISSUE THREAD

**Issue by cdolfi** [sandiego-rh/sandiego#60]
For the Open Source Summit there needs to be a jupyter book generated from a selection of the notebooks 

Acceptance Criteria:

- [ ] Determine if a new repo/notebook should be made for this events
- [ ] Render a jupyterbook for the event

**Comment by isabelizimm** [comment]
we can just edit the `_toc.yaml` to only show the notebooks you want for this event. The drawback is that version of the book would not be persistent long-term, which might be okay anyway as this project is growing and changing
