### ISSUE TITLE
Email/Messaging to get general feedback and project list

### ISSUE THREAD

**Issue by cdolfi** [sandiego-rh/sandiego#65]
Writing out a email/message to be send out on lists with the focus on informing people on our development cycle, how to get involved/give feedback, and on getting historical "emerging projects" list 

Acceptance criteria(more to be added):

- [x] Overview on the last sprint with [video](https://drive.google.com/file/d/1RLD88ogIoEcR0ywrLp1y7SJ4smIs1DNX/view?usp=sharing), [demo doc](https://docs.google.com/document/d/1FrKsebcEhjoS5u1cn5mqx4rhXzvC383nJEkq0IFdoQA/edit?usp=sharing)
- [x] include project [description](https://docs.google.com/document/d/1486eDUsHAOmz2NGsKsaj56MeGKh1ZS-TE6GD-sbiMRA/edit?usp=sharing)
- [x] links to [matrix page](https://matrix.to/#/#sandiego-rh:matrix.org)
- [x] description on planning process 
- [x] how to give feedback 
- [x] a form for people to fill out on projects 
- [x] Discuss options for continuous messaging
- [x] Determining where this message should be sent to 
- [x] generating form/formatting google sheet

**Comment by JamesKunstle** [comment]
w.r.t "a form for people to fill out on projects": I'm interested in how we define projects of interest. How do we frame a question that effectively articulates the goal of "I want to find repositories/projects that became very important"?

Our goal, of course, would be to find those projects that became important to important technologies / processes. But if we cast a narrow net such as the one above, we might under-fill a useful project list. We ought to have a call about this + we might need the joint support of a data engineer and an expert in open source communities.

**Comment by cdolfi** [comment]
@JamesKunstle There has been a few ideas that have been thrown around on this. A conversation between myself and @quaid came up with a framing like "what would you wish sandiego had found for you if it had existed and when?" and then say, "ultimately i'm looking for a list of projects that ended up developing into something that people/companies used and depended on and in some way influenced the landscape."

**Comment by semioticrobotic** [comment]
I took a first pass at a draft communication that incorporates some of the above. All feedback welcome. Feel free to slice, dice, and Frankenstein any part(s) of this together.

```
Subject: Help us glimpse the future

Upstream open source participation grants Red Hat one of its superpowers: the ability to spot technological trends and innovations while they're still taking shape. We help customers identify, track, and respond to these changes—so that today's small experiment doesn't catch them off-guard when it becomes tomorrow's major industry disruption.

And now you can help us hone that superpower by contributing to a new open source project: Project Sandiego.

Project Sandiego will discover information from open source-ecosystem datasets that can help drive community- and business-oriented decision making for Red Hat, including the Office of the CTO’s Open Source Program Office and Emerging Technology teams. It will enable contributors and observers to ask questions and make data-informed decisions about open source projects and communities, as well as enable business units make clearer decisions about investing resources into new and existing open source projects.

In short? It helps us glimpse the future as while it's still coming into focus.

Now we need your help to get it ready for launch. Here's how you can get involved.

Here's how to get started:

- Read about the project's mission and vision [^1]
- Join the project community on GitHub and Matrix [^2]

Then you can assist with our most pressing need: teaching Sandiego what a successful open source project looks like.

For Sandiego to be able to spot *future* open source projects, we need to show it what *past* open source projects look like. If you've got a great example to share—a project that once made you say "I really I'd known about that before it took off" or "Why didn't I see that one coming?"—use our form to tell us about it.[^3]

Want to see Project Sandiego in action? View our demo video to learn more.[^4]

Thanks for your help,

{signed}

[^1] URL
[^2] URL
[^3] URL
[^4] URL
```

**Comment by cdolfi** [comment]
@semioticrobotic You're awesome, seriously. Ive been struggling to get anything on paper for days now. I made a doc to put some comments in it as notes on things im noodling on. Let me know if you have thoughts on any of the comments! https://docs.google.com/document/d/1rOrzpdCkkD0pE5BCDiJ4CdS-VET0nQc0h2ZIZwNYvH0/edit?usp=sharing

**Comment by semioticrobotic** [comment]
Great comments. Thanks, @cdolfi. I incorporated all the feedback and posed one follow-up for you to consider.
