### ISSUE TITLE
Test Superset connection

### ISSUE THREAD

**Issue by cdolfi** [sandiego-rh/sandiego#87]
Now that we are setting up Augur on the community cage, we need to test how to connect the DB to the Superset tool on Operate First cloud. 

Acceptance Criteria

- [x] Determine if we need to connect with anyone on the Opt1st side to help
- [x] Test the ability to access the DB from superset 
- [x] Troubleshoot until solution found if possible

**Comment by hemajv** [comment]
The Augur DB is now accessible from Trino/Superset :tada: It can be found as `ospo_sandiego` catalog. Whenever you need to interact with it, ensure you are selecting this catalog name.

- You can interact with the DB by using CloudBeaver: http://cloudbeaver-opf-trino.apps.smaug.na.operate-first.cloud/ (reach out to opf team for credentials)
- Dashboards can be created in Superset: https://superset.operate-first.cloud/ by following [this guide](https://www.operate-first.cloud/hitchhikers-guide/apps/docs/odh/trino/trino_superset_user_guide.md)

**Comment by cdolfi** [comment]
Wooo!!
