### ISSUE TITLE
New Visualization: Active Contributor Count 

### ISSUE THREAD

**Issue by cdolfi** [sandiego-rh/sandiego#89]
**Please describe the background and context for this new visualization**
how many “active” contributors are there in a community at any given time/currently

**Describe the perspective you'd like the final visual to give**

**Describe the acceptance criteria for the issue and visualization to be complete**
A clear and concise list of task that need to be completed and if applicable links to smaller issues that build into this one. 

**Additional context**

**REMINDER:** 
Before a visualization issue can be closed, there must be clear documentation on the notebook of the decisions made at each step and the "why." Also,
any ml ideas generated from this process should be created into as issue with the ml request tag**

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
**Progress-log**

- [x] For each contributor, grab all of the events in the set (Commits, PRs/Changesets/Issues). 
- [x] For contributors of a project, find the most recent (Commits, PRs/Changesets/Issues) event. This will be enough information to tell whether the user is in the "drifting away" or "active" population currently.
- [x] Scrub through timeline of repo to measure time-longitudinal active contributor count. e.g. for time 't' in the project's history, what are the active and drifting population counts? 
- [x] Decide whether there ought to be a category for those contributors who have not contributed in a significant amount of time, e.g. x_cat > drifting_away > active.

**Comment by JamesKunstle** [comment]
**Note:** LF Dashboard makes the following definitions:

"Contributors performing code activity (Commits, PRs/Changesets/Issues) within the last 1 year are active code contributors."

and

"Active Contributors who did not perform any code activity in the last 6 months are considered as drifting away."

These seem to be reasonable definitions even if the time-span is arbitrary. In the future, it would likely be better to have some repository-specific metadata defining these two populations. E.g. If the average "code-activity" frequency of users is about once a year, a contributor ought to be considered active until their activity is statistically unlikely to be that of an active contributor. We could also go off of changes in "code-activity" per user but that seems to be too fine-grained. Could be useful, though.

**Comment by cdolfi** [comment]
@JamesKunstle is this ready to be closed?

**Comment by JamesKunstle** [comment]
Yes I think so- future work will be done with more survival analysis (e.g. competing hazards) but for this specific issue, we are done.

**Comment by JamesKunstle** [comment]
I'm going to be done with this issue soon @cdolfi I need some help working with the way that Github handles PR's w.r.t changes that have happened since a branch has been made, i.e. I don't want to remerge things that have already been merged to main but that don't exist on my feature branch. Will handle after 1/1/22

**Comment by cdolfi** [comment]
@JamesKunstle Sounds good!
