### ISSUE TITLE
New Visualization: PRs merged automatically

### ISSUE THREAD

**Issue by hemajv** [sandiego-rh/sandiego#90]
**Please describe the background and context for this new visualization**

In the [performance notebook](https://github.com/sandiego-rh/sandiego/blob/main/notebooks/performance/pr_performance.ipynb), we are visualizing the mean time to first response on a PR based on comments being answered or unanswered. However, we did not consider the possibility of PRs being automatically merged (for example by bots). It would be useful to capture this information as well.

**Describe the perspective you'd like the final visual to give**
A pie chart showing the response percentage for both manual and automatically merged PRs

**Comment by cdolfi** [comment]
I did not find much results for PRs merged automatically, but I was able to look a bit into automatic responses. Will be taking the visualization that way
