### ISSUE TITLE
Sprint 6: Discussion and planning on next visualizations and metric

### ISSUE THREAD

**Issue by cdolfi** [sandiego-rh/sandiego#98]
This is a part of the extended series of development for dashboard visualizations. Let this be the place where people can put their new ideas for visualizations or to voice the questions they would like to see answered.

For each sprint cycle, the following criteria must be met: 

- [x] 2 (or more) new potential visualization or metrics 
- [x] 2 proposed visualizations generated into a detailed issue to be assigned the next sprint 
- [x] Discussions in this issue condensed into the following [document](https://docs.google.com/document/d/1Jzg0P7DivFsKgMgvGEzMI6C8jn8ypw8x4EvlUYUBXYU/edit?usp=sharing)

**Comment by cdolfi** [comment]
Some potential ideas from some work on the chaoss side: 
-https://chaoss.community/metric-license-coverage/
-https://chaoss.community/metric-code-of-conduct/
-https://chaoss.community/metric-license-declared/
-https://chaoss.community/metric-test-coverage/
-https://chaoss.community/metric-bus-factor/
-https://chaoss.community/metric-elephant-factor/

**Comment by cdolfi** [comment]
@thewizzy Curious if you have any thoughts on this

**Comment by cdolfi** [comment]
Another idea: Looking at the response/close rate to issues with the bug/defect tag

**Comment by cdolfi** [comment]
Update: will be hosting a discussion around the topic of "What is the first question you have when initially see/hear of an open source community?" with the hopes to get more guidance on this at the next Community Architects CoP

**Comment by thewizzy** [comment]
Age and activity on pull requests? Could be part of the story of how receptive the project is to contributions.

**Comment by cdolfi** [comment]
@thewizzy can you elaborate a bit?

**Comment by thewizzy** [comment]
By looking at the Pull Requests for a project and consider a few of the attributes of them:
* Who created it?
* How old it is?
* How much activity the PR has had (comments, reviews etc)?
* Who, if anyone is responding to the PR?
* How many PR are there and what is the spread of creation dates?
* How many have been merged between those remaining?

By looking at these data points we could answer a few questions:
* Is the project merging any new code?
* How receptive are they to new contributions/Contributors? (Are they merging PRs by existing contributors and ignoring new contributors PRs?)

Could be useful for determining the general speed with which they would merge code but more importantly, how open they are to input from the community.

**Comment by cdolfi** [comment]
https://github.com/sandiego-rh/sandiego/blob/main/notebooks/pr_activity.ipynb
https://github.com/sandiego-rh/sandiego/blob/main/notebooks/performance/pr_performance.ipynb
https://github.com/sandiego-rh/sandiego/blob/main/notebooks/performance/pr_delta.ipynb

Would any combination of these cover what you are thinking?

**Comment by thewizzy** [comment]
> https://github.com/sandiego-rh/sandiego/blob/main/notebooks/performance/pr_performance.ipynb 
> https://github.com/sandiego-rh/sandiego/blob/main/notebooks/performance/pr_delta.ipynb

These two in particular answer at least half of the attributes. The augur schema looks like it could be used to answer the rest. 

Of the two questions, the first is pretty easy, if they have a PR merged in x time frame, they are merging new code. The second is probably more interesting to look at. In the meeting a few days ago one of the notebooks shared (I think James') was looking at contributors over time. How receptive a project is to new contributors will possibly influence that and could be useful as a health metric.
